import{S as q,a as x,i as p}from"./assets/vendor-5401a4b0.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const c=document.querySelector("form"),u=document.querySelector(".js-gallery-elem"),g=document.querySelector(".loader"),h=document.querySelector(".js-load-more");let y="",a=1,d=0,m=0;const P=new q(".gallery a",{captionDelay:250});c.addEventListener("submit",$);async function $(o){o.preventDefault(),w(),l(),y=c.elements.query.value.trim(),a=1,u.innerHTML="";const s=await L();d=Math.ceil(s.totalHits/s.hits.length),v(),b(s.hits),f(),c.reset()}async function L(){const o="https://pixabay.com/api/",n={params:{key:"42153847-0f7baac2d7b2e92d7ce6bbe8e",q:`${y}`,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:a}};try{const r=await x.get(o,n);return r.data.total===0?(M(),l()):(console.log(r.data),r.data)}catch{console.log("Результатів не знайдено.")}}h.addEventListener("click",B);async function B(){l(),w(),a+=1;const o=await L();b(o.hits),f(),v(),window.scrollBy({top:j(),behavior:"smooth"})}function b(o){const s=o.map(({largeImageURL:n,webformatURL:r,tags:e,likes:t,views:i,comments:E,downloads:S})=>` <div class="gallery">
    <a href="${n}"><div class="thumb"><img src="${r}" alt="${e}" title="${e}" width = "360px"
      height = "300px"/>
       <ul class="info-cards-container">
      <li class="info-cards-elements">likes<span>${t}</span></li>
      <li class="info-cards-elements">views<span>${i}</span></li>
       <li class="info-cards-elements">comments<span>${E}</span></li>
       <li class="info-cards-elements">downloads<span>${S}</span></li>
     </ul>
     </div>
      </a>
    </div>`).join("");u.insertAdjacentHTML("beforeend",s),P.refresh()}function M(){u.innerHTML="",l(),f(),c.reset(),p.show({message:'❌ "Sorry, there are no images matching your search query. Please try again!',color:"red",position:"topRight",maxWidth:"400px",timeout:"3000"})}function O(){p.show({message:"We're sorry, but you've reached the end of search results.",color:"blue",position:"topRight",maxWidth:"400px"})}function v(){const o=a===d;console.log(o),console.log(a),console.log(d),o?O():H()}function H(){h.classList.remove("is-hidden")}function l(){h.classList.add("is-hidden")}function w(){g.classList.remove("is-hidden")}function f(){g.classList.add("is-hidden")}function j(){return m=document.querySelector(".thumb").getBoundingClientRect().height*2,m}
//# sourceMappingURL=commonHelpers.js.map
