import{S as P,a as q,i as p}from"./assets/vendor-5401a4b0.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const c=document.querySelector("form"),u=document.querySelector(".js-gallery-elem"),g=document.querySelector(".loader"),h=document.querySelector(".js-load-more");let y="",a=1,d=0,f=0;const x=new P(".gallery a",{captionDelay:250});c.addEventListener("submit",$);async function $(r){r.preventDefault(),w(),l(),y=c.elements.query.value.trim(),a=1,u.innerHTML="";try{const o=await L();d=Math.ceil(o.totalHits/o.hits.length),d>=a?(b(o.hits),v()):M()}catch{console.log("error")}m(),c.reset()}async function L(){const r="https://pixabay.com/api/",n={params:{key:"42153847-0f7baac2d7b2e92d7ce6bbe8e",q:`${y}`,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:a}};try{return(await q.get(r,n)).data}catch{console.log("Результатів не знайдено.")}}h.addEventListener("click",B);async function B(){l(),w(),a+=1;const r=await L();b(r.hits),m(),v(),window.scrollBy({top:j(),behavior:"smooth"})}function b(r){const o=r.map(({largeImageURL:n,webformatURL:s,tags:e,likes:t,views:i,comments:E,downloads:S})=>` <div class="gallery">
    <a href="${n}"><div class="thumb"><img src="${s}" alt="${e}" title="${e}" width = "360px"
      height = "300px"/>
       <ul class="info-cards-container">
      <li class="info-cards-elements">likes<span>${t}</span></li>
      <li class="info-cards-elements">views<span>${i}</span></li>
       <li class="info-cards-elements">comments<span>${E}</span></li>
       <li class="info-cards-elements">downloads<span>${S}</span></li>
     </ul>
     </div>
      </a>
    </div>`).join("");u.insertAdjacentHTML("beforeend",o),x.refresh()}function M(){u.innerHTML="",l(),m(),c.reset(),p.show({message:'❌ "Sorry, there are no images matching your search query. Please try again!',color:"red",position:"topRight",maxWidth:"400px",timeout:2500})}function O(){l(),p.show({message:"We're sorry, but you've reached the end of search results.",color:"blue",position:"topRight",maxWidth:"400px",timeout:2500})}function v(){a===d?O():H()}function H(){h.classList.remove("is-hidden")}function l(){h.classList.add("is-hidden")}function w(){g.classList.remove("is-hidden")}function m(){g.classList.add("is-hidden")}function j(){return f=document.querySelector(".thumb").getBoundingClientRect().height*2,f}
//# sourceMappingURL=commonHelpers.js.map
